# Generated by Django 5.1.15 on 2026-03-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_status_alter_game_player_two'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='board_state',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='game',
            name='hand_letters',
            field=models.JSONField(default=list),
        ),
    ]
