# Generated by Django 5.1.15 on 2026-03-17 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_board_state_game_hand_letters'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='hand_letters',
            new_name='player_one_hand',
        ),
        migrations.AddField(
            model_name='game',
            name='current_turn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_turn_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='player_one_pile',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='game',
            name='player_two_hand',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='game',
            name='player_two_pile',
            field=models.JSONField(default=list),
        ),
    ]
