# Generated by Django 5.1.15 on 2026-03-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_rename_hand_letters_game_player_one_hand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player_one_deck',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='game',
            name='player_two_deck',
            field=models.JSONField(default=list),
        ),
    ]
